function newTraces = removeDecay(traces, time, ...
    window_decay, window_correct, threshold)

newTraces = traces;

timeBin = median(diff(time));
indUnits = ...
    find(mean(traces(1:round(window_decay / timeBin),:), 1, 'omitnan') > ...
    mean(traces, 1, 'omitnan') + ...
    threshold .* std(traces, 0, 1, 'omitnan'));
ind = round(window_correct / timeBin);
for iUnit = 1:length(indUnits)
    y = traces(1:ind, indUnits(iUnit));
    y = fillmissing(y, 'linear');
    % fit double exponential to start of trace
    f = fit((1:length(y))', y, ...
        @(a,b,c,d,e,x) a + b .* exp(-x ./ c) + d .* exp(-x ./ e), ...
        'Lower', [0 0 0 0 0], ...
        'Upper', [max(y) max(y) 500 max(y) 500], ...
        'StartPoint', [min(y) mean(y) 50 mean(y) 5]);
    % remove fit
    newTraces(:, indUnits(iUnit)) = newTraces(:, indUnits(iUnit)) - ...
        f(1 : size(traces,1)) + f.a;
end